eden:
    integration:
        logstash:
            enabled: false
        swagger:
            default-include-pattern: /(api|config)/.*
            title: #project.description#
            version: #project.version#
    security:
        jwt:
            authentication:
                base64-secret: MjEyMzJmMjk3YTU3YTVhNzQzODk0YTBlNGE4MDFmYzMyMTIzMmYyOTdhNTdhNWE3NDM4OTRhMGU0YTgwMWZjMw==
            authorization:
                header: JwtAuthorization
        oauth2:
            authorization:
                access-token-uri: http://uaa/oauth/token
                access-token-uri-service-id: uaa
                client-credentials:
                    client-id: client
                    client-secret: client
                password:
                    client-id: password
                    client-secret: password
                public-token-key-uri: http://uaa/oauth/token_key
                public-token-key-uri-service-id: uaa

logging:
    file: target/${spring.application.name}.log
    level:
        ROOT: INFO
        org.ylzl.eden: DEBUG

eureka:
    client:
        fetch-registry: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
        service-url:
            defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        hostname: localhost
        lease-expiration-duration-in-seconds: 10
        lease-renewal-interval-in-seconds: 5
    metadata-map:
        user:
            name: ${security.user.name}
            password: ${security.user.password}
    server:
        enable-self-preservation: false

security:
    user:
        name: admin
        password: 21232f297a57a5a743894a0e4a801fc3
        roles: ROLE_ADMIN

server:
    port: 8761

spring:
    boot:
        admin:
            username: ${security.user.name}
            password: ${security.user.password}
            turbine:
                url: http://localhost:${server.port}/turbine.stream
    zipkin:
        base-url: http://localhost:9411
        enabled: false
